INSERT INTO USERS
(ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, EMAIL, ENABLED, PASSWORD)
VALUES (TRUE, TRUE, TRUE, 'alicia@test.com', TRUE, '$2a$10$7eSfXu48ngO1VEMKQCb5EOJfDDZL3fRe6HJhEtLdSHzuC/x7DZdZG');