INSERT INTO USERS
(ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, EMAIL, ENABLED, PASSWORD)
VALUES (TRUE, TRUE, TRUE, 'alicia@test.com', TRUE, '$2a$10$7eSfXu48ngO1VEMKQCb5EOJfDDZL3fRe6HJhEtLdSHzuC/x7DZdZG'),
       (TRUE, TRUE, TRUE, 'bernardo@test2.com', TRUE, '$2a$10$7eSfXu48ngO1VEMKQCb5EOJfDDZL3fRe6HJhEtLdSHzhC/x7DZdZG');

INSERT INTO GROUPS
    (NAME)
VALUES ('testGroup'),
       ('testGroup2');

INSERT INTO GROUPS_USERS
    (GROUP_ID, USERS_ID)
VALUES (1, 1)