services:
  web:
    image: front
    restart: always
    environment: 
      - API_URL=http://localhost:8080
    ports:
      - "3000:80"
  back:
    image: back
    restart: always
    ports:
      - "8080:8080"