/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/login": {
    post: operations["loginByPassword"];
  };
  "/groups": {
    post: operations["createNewGroup"];
  };
  "/groups/{groupId}/spendings": {
    post: operations["createNewSpending"];
  };
  "/users/{id}/groups": {
    get: operations["getUserGroups"];
  };
  "/users/current": {
    get: operations["getCurrentUser"];
  };
  "/groups/{id}": {
    get: operations["getGroupById"];
  };
  "/groups/{id}/spendings": {
    get: operations["getGroupSpendings"];
  };
  "/groups/{id}/members": {
    get: operations["getGroupMembersById"];
  };
}

export interface components {
  schemas: {
    ApiError: {
      error?: string;
      timestamp?: string;
      details?: string;
    };
    LoginData: {
      email?: string;
      password?: string;
    };
    CreateGroupData: {
      name?: string;
    };
    SpendigData: {
      name?: string;
      /** Format: double */
      amount?: number;
      /** Format: int64 */
      userId?: number;
    };
    Group: {
      /** Format: int64 */
      id?: number;
      name?: string;
      users?: components["schemas"]["User"][];
    };
    User: {
      /** Format: int64 */
      id?: number;
      email?: string;
      username?: string;
    };
    Spending: {
      /** Format: int64 */
      id?: number;
      name?: string;
      /** Format: double */
      amount?: number;
      group?: components["schemas"]["Group"];
      user?: components["schemas"]["User"];
    };
    Member: {
      /** Format: int64 */
      id: number;
      email: string;
      /** Format: double */
      totalSpent: number;
    };
  };
}

export interface operations {
  loginByPassword: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": string;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginData"];
      };
    };
  };
  createNewGroup: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": number;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGroupData"];
      };
    };
  };
  createNewSpending: {
    parameters: {
      path: {
        groupId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": number;
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpendigData"];
      };
    };
  };
  getUserGroups: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["Group"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getCurrentUser: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getGroupById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["Group"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getGroupSpendings: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["Spending"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
  };
  getGroupMembersById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["Member"][];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
      /** Not Found */
      404: {
        content: {
          "*/*": components["schemas"]["ApiError"];
        };
      };
    };
  };
}

export interface external {}
