name: CI/CD
on: push
jobs:
  ci-tests:
    uses: ./.github/workflows/deploy-and-test.yml
    with: 
      ENV_NAME: continous-integration
      DEPLOY: false

      API_URL: http://localhost:8080
      BASE_URL: http://localhost:3000
      
      BACKEND_IMAGE_NAME: back
      FRONTEND_IMAGE_NAME: front
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  deploy-pre-and-test:
    uses: ./.github/workflows/deploy-and-test.yml
    needs: ci-tests
    with: 
      ENV_NAME: pre-production
      DEPLOY: true 

      API_URL: https://pre-back.tfg.joangaliana.com
      BASE_URL:  https://pre-tfg.joangaliana.com
      
      BACKEND_IMAGE_NAME: ghcr.io/joangaliana/tfg-back-pre
      FRONTEND_IMAGE_NAME: ghcr.io/joangaliana/tfg-front-pre
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_DEPLOY_CMD: ${{ secrets.SSH_DEPLOY_CMD }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  deploy-prod-and-test:
    uses: ./.github/workflows/deploy-and-test.yml
    needs: deploy-pre-and-test
    with: 
      ENV_NAME: production
      DEPLOY: true
    
      API_URL: https://back.tfg.joangaliana.com
      BASE_URL: https://tfg.joangaliana.com
    
      BACKEND_IMAGE_NAME: ghcr.io/joangaliana/tfg-back
      FRONTEND_IMAGE_NAME: ghcr.io/joangaliana/tfg-front
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_DEPLOY_CMD: ${{ secrets.SSH_DEPLOY_CMD }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} 