name: Application tests
on: [push]
jobs:
  e2e-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Start containers
        run: docker-compose -f "./e2e/docker-compose.yml" up -d --build
      
      - name: Run end to end tests
        run: |
          cd ./e2e/;
          npm start;