name: Application tests
on: [push]

env:
  BACKEND_PRE_IMAGE_NAME: ghcr.io/joangaliana/tfg-back-pre
  FRONTEND_PRE_IMAGE_NAME: ghcr.io/joangaliana/tfg-front-preç
  PRE_BASE_URL: tfg.joangaliana.com
  PRE_API_URL: back.tfg.joangaliana.com

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build front image
        uses: docker/build-push-action@v2
        with:
          context: ./front
          push: false
          tags: front
          load: true
          cache-from: type=gha,scope=front
          cache-to: type=gha,mode=max,scope=front
      
      - name: Build back image
        uses: docker/build-push-action@v2
        with:
          context: ./back
          push: false
          tags: back
          load: true
          cache-from: type=gha,scope=back
          cache-to: type=gha,mode=max,scope=back

      - name: Start containers
        run: docker-compose -f "./e2e/docker-compose.yml" up -d --no-build
      
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
          record: true
          tag: GHA
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pre-and-test:
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./front
          push: true
          tags: ${{ env.FRONTEND_PRE_IMAGE_NAME }}
          cache-from: type=gha,scope=front
          cache-to: type=gha,mode=max,scope=front
      
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./back
          push: true
          tags: ${{ env.BACKEND_PRE_IMAGE_NAME }}
          cache-from: type=gha,scope=back
          cache-to: type=gha,mode=max,scope=back

      - name: Run e2e tests on pre
        uses: cypress-io/github-action@v2
        with:
          record: true
          tag: GHA-PRE
          working-directory: e2e
          env: backendURL=${{ env.PRE_API_URL }}
          config: baseUrl=${{ env.PRE_BASE_URL }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          