name: Application tests
on: [push]
jobs:
  e2e-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build front image
        uses: docker/build-push-action@v2
        with:
          context: ./front
          file: Dockerfile
          push: false
          tags: front
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start containers
        run: docker-compose -f "./e2e/docker-compose.yml" up -d --build
      
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e